name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          version: '0.8.19'
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --extra docs
      - name: Build docs
        run: mkdocs build
      - name: Rebuild and deploy docs
        run: mkdocs gh-deploy --force
        if: github.ref == 'refs/heads/main' && steps.build_docs.outcome == 'success'
