name: tests
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: '0.8.19'
          enable-cache: true

      - name: Sync project (dev + extras)
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: |
          uv run pytest -v --maxfail=1 \
            --cov=asaf \
            --cov-report=xml \
            --cov-report=term-missing \
            tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
